--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: CVS understands 'HEAD' to refer to the latest revision in the repository.
full_name: Capistrano::Deploy::SCM::Cvs#head
is_singleton: false
name: head
params: ()
visibility: public
