--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RI::MethodSummary 
  name: run
comment: 
constants: []

full_name: Merb::ApplicationGenerator
includes: []

instance_methods: []

name: ApplicationGenerator
superclass: Object
