--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: RubiGen::Lookup::ClassMethods#application_sources
is_singleton: false
name: application_sources
params: (filters = [])
visibility: public
