--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Use application generators (app, ?).
full_name: RubiGen::Lookup::ClassMethods#use_application_sources!
is_singleton: false
name: use_application_sources!
params: (*filters)
visibility: public
