--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: An abstract superclass, which forms the base for all deployment strategies which work by grabbing the code from the repository directly from remote host. This includes deploying by checkout (the default), and deploying by export.
constants: []

full_name: Capistrano::Deploy::Strategy::Remote
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: check!
- !ruby/object:RI::MethodSummary 
  name: check!
- !ruby/object:RI::MethodSummary 
  name: command
- !ruby/object:RI::MethodSummary 
  name: command
- !ruby/object:RI::MethodSummary 
  name: deploy!
- !ruby/object:RI::MethodSummary 
  name: deploy!
- !ruby/object:RI::MethodSummary 
  name: mark
- !ruby/object:RI::MethodSummary 
  name: mark
- !ruby/object:RI::MethodSummary 
  name: scm_run
- !ruby/object:RI::MethodSummary 
  name: scm_run
name: Remote
superclass: Base
