--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: An abstract method which must be overridden in subclasses, to return the actual SCM command(s) which must be executed on each target host in order to perform the deployment.
full_name: Capistrano::Deploy::Strategy::Remote#command
is_singleton: false
name: command
params: ()
visibility: protected
