--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "Runs the given command, filtering output back through the #handle_data filter of the SCM implementation."
full_name: Capistrano::Deploy::Strategy::Remote#scm_run
is_singleton: false
name: scm_run
params: (command)
visibility: protected
