--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: Raised when you have incorrectly configured Vlad.
constants: []

full_name: Vlad::ConfigurationError
includes: []

instance_methods: []

name: ConfigurationError
superclass: Error
