--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: Implements the deployment strategy that keeps a cached checkout of the source code on each remote server. Each deploy simply updates the cached checkout, and then does a copy from the cached copy to the final deployment location.
constants: []

full_name: Capistrano::Deploy::Strategy::RemoteCache
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: check!
- !ruby/object:RI::MethodSummary 
  name: check!
- !ruby/object:RI::MethodSummary 
  name: deploy!
- !ruby/object:RI::MethodSummary 
  name: deploy!
name: RemoteCache
superclass: Remote
