--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: Implements the Capistrano SCM interface for the Perforce revision control system (http://www.perforce.com).
constants: []

full_name: Capistrano::Deploy::SCM::Perforce
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: checkout
- !ruby/object:RI::MethodSummary 
  name: checkout
- !ruby/object:RI::MethodSummary 
  name: diff
- !ruby/object:RI::MethodSummary 
  name: diff
- !ruby/object:RI::MethodSummary 
  name: export
- !ruby/object:RI::MethodSummary 
  name: export
- !ruby/object:RI::MethodSummary 
  name: handle_data
- !ruby/object:RI::MethodSummary 
  name: handle_data
- !ruby/object:RI::MethodSummary 
  name: head
- !ruby/object:RI::MethodSummary 
  name: head
- !ruby/object:RI::MethodSummary 
  name: log
- !ruby/object:RI::MethodSummary 
  name: log
- !ruby/object:RI::MethodSummary 
  name: query_revision
- !ruby/object:RI::MethodSummary 
  name: query_revision
- !ruby/object:RI::MethodSummary 
  name: sync
- !ruby/object:RI::MethodSummary 
  name: sync
name: Perforce
superclass: Base
