--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Returns the command that will do an &quot;svn diff&quot; for the two revisions.
full_name: Capistrano::Deploy::SCM::Subversion#diff
is_singleton: false
name: diff
params: (from, to=nil)
visibility: public
