--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Capistrano::Deploy::RemoteDependency#file
is_singleton: false
name: file
params: (path, options={})
visibility: public
