--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: For mercurial HEAD == tip except that it bases this assumption on what tip is in the current repository (so push before you deploy)
full_name: Capistrano::Deploy::SCM::Mercurial#head
is_singleton: false
name: head
params: ()
visibility: public
