--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "An alternative way to associate servers with roles. If you have a server that participates in multiple roles, this can be a DRYer way to describe the relationships. Pass the host definition as the first parameter, and the roles as the remaining parameters:"
- !ruby/struct:SM::Flow::VERB 
  body: "  server &quot;master.example.com&quot;, :web, :app\n"
full_name: Capistrano::Configuration::Roles#server
is_singleton: false
name: server
params: (host, *roles)
visibility: public
