--- !ruby/object:RI::ClassDescription 
attributes: 
- !ruby/object:RI::Attribute 
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: The options available for this SCM instance to reference. Should be treated like a hash.
  name: configuration
  rw: R
- !ruby/object:RI::Attribute 
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: The options available for this SCM instance to reference. Should be treated like a hash.
  name: configuration
  rw: R
class_methods: 
- !ruby/object:RI::MethodSummary 
  name: default_command
- !ruby/object:RI::MethodSummary 
  name: default_command
- !ruby/object:RI::MethodSummary 
  name: new
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:SM::Flow::P 
  body: The ancestor class for all Capistrano SCM implementations. It provides minimal infrastructure for subclasses to build upon and override.
- !ruby/struct:SM::Flow::P 
  body: Note that subclasses that implement this abstract class only return the commands that need to be executed--they do not execute the commands themselves. In this way, the deployment method may execute the commands either locally or remotely, as necessary.
constants: []

full_name: Capistrano::Deploy::SCM::Base
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: checkout
- !ruby/object:RI::MethodSummary 
  name: checkout
- !ruby/object:RI::MethodSummary 
  name: command
- !ruby/object:RI::MethodSummary 
  name: command
- !ruby/object:RI::MethodSummary 
  name: diff
- !ruby/object:RI::MethodSummary 
  name: diff
- !ruby/object:RI::MethodSummary 
  name: handle_data
- !ruby/object:RI::MethodSummary 
  name: handle_data
- !ruby/object:RI::MethodSummary 
  name: head
- !ruby/object:RI::MethodSummary 
  name: head
- !ruby/object:RI::MethodSummary 
  name: local
- !ruby/object:RI::MethodSummary 
  name: local
- !ruby/object:RI::MethodSummary 
  name: local?
- !ruby/object:RI::MethodSummary 
  name: local?
- !ruby/object:RI::MethodSummary 
  name: log
- !ruby/object:RI::MethodSummary 
  name: log
- !ruby/object:RI::MethodSummary 
  name: next_revision
- !ruby/object:RI::MethodSummary 
  name: next_revision
- !ruby/object:RI::MethodSummary 
  name: query_revision
- !ruby/object:RI::MethodSummary 
  name: query_revision
- !ruby/object:RI::MethodSummary 
  name: sync
- !ruby/object:RI::MethodSummary 
  name: sync
name: Base
superclass: Object
