--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "Returns true if running in &quot;local&quot; mode. See #local."
full_name: Capistrano::Deploy::SCM::Base#local?
is_singleton: false
name: local?
params: ()
visibility: public
