--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Resynchronize the working copy in <tt>destination</tt> to the specified <tt>revision</tt>.
full_name: Capistrano::Deploy::SCM::Base#sync
is_singleton: false
name: sync
params: (revision, destination)
visibility: public
